version: '3.8'

services:
  jenkins:
    image: myjenkins-blueocean:2.452.2-1
    container_name: jenkins-blueocean-test
    restart: on-failure
    networks:
      - jenkins
    volumes:
      - /run/host-services/docker.proxy.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"

  nginx:
    image: nginx:latest
    container_name: nginx-test
    networks:
      - jenkins
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro 

  sonarqube:
    image: sonarqube:latest 
    container_name: sonarqube-test
    networks:
      - jenkins
    ports:
      - "9000:9000"

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
